function retval = RombergIntegration(f, a, b, n, m)
  ns = n .^ (1:m);
  hs = (b - a) ./ (ns - 1);
  retval = NevilleSchema( ...
    hs .^ 2, ...
    arrayfun(@(n) compositeTrapezoidal(f, a, b, n), ns), ...
    0 ...
  );
end
