name: Flake checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = flakes nix-command pipe-operators
      - name: flake check
        run: nix flake check --all-systems
